// Code generated by antithesis-go-instrumentor; DO NOT EDIT.

package main

// ----------------------------------------------------
// Antithesis LLC Go Instrumentor 0.6.0
//
// Assertion Catalog
//
// Generated on Thu Mar 19 17:22:56 EDT 2026
// ----------------------------------------------------

import "github.com/antithesishq/antithesis-sdk-go/assert"

func init() {

  const condFalse = false
  const condTrue = true
  const wasHit = true
  const notHit = !wasHit
  const mustBeHit = true

  const universalTest = "always"

  const reachabilityTest = "reachability"

  var noDetails map[string]any = nil

  // Reachable(message, details)
  assert.AssertRaw(condTrue, "reached the else branch", noDetails, "example.com/e2e-test", "foo", "main.go", 14, notHit, mustBeHit, reachabilityTest, "Reachable", "reached the else branch")

  // Always(cond, message, details)
  assert.AssertRaw(condFalse, "always in main", noDetails, "example.com/e2e-test", "main", "main.go", 20, notHit, mustBeHit, universalTest, "Always", "always in main")
}






