package zad602425a68e

// ----------------------------------------------------
// Generated by Antithesis instrumentor - do not modify
// ----------------------------------------------------

import "github.com/antithesishq/antithesis-sdk-go/instrumentation"

func init() {
	instrumentation.InitializeModule("go-ad602425a68e.sym.tsv", 4)
}

func Notify(edge int) {
	instrumentation.Notify(edge)
}

